# Generated by Django 4.2.2 on 2023-07-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_resultado_ejecutando'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='plagio',
            field=models.JSONField(default=list),
        ),
    ]
