# Generated by Django 4.2.2 on 2023-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_resultado_plagio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='informacion',
            field=models.JSONField(default=dict),
        ),
    ]
